<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-15GBQEPO" failures="1" tests="4" name="Default test(failed)" time="0.075" errors="0" timestamp="2024-08-03T10:48:17 IST">
  <testcase classname="testng.RetryTest" name="demo" time="0.012">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.001">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.001">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.RetryTest.demo(RetryTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
</testsuite> <!-- Default test(failed) -->
